FitTrackee/FitTrackee/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.auth.decorators import user_passes_test

from FitTrackee import settings
from apps.user import views as user_view
from apps.home import views as home_view

login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/home')
anonymous_forbidden = user_passes_test(lambda u: u.is_authenticated(), '/login')

urlpatterns = [
    url(r'^login/$', login_forbidden(auth_views.login), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^register/$', login_forbidden(user_view.register), name='register'),
    url(r'^users/', include('apps.users.urls')),
    url(r'^user/', include('apps.user.urls')),
    url(r'^activities/', include('apps.activities.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/',  include('apps.home.urls')),
    url(r'^profile/$', user_view.profile, name='profile'),
    url(r'^api/', include('apps.api.urls')),
    url(r'^$', anonymous_forbidden(home_view.index)),
] + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FitTrackee/apps/activities/urls.py
from django.conf.urls import url

from . import views

app_name = 'activities'
urlpatterns = [
    url(r'^add/', views.add_activity, name='add'),
    url(r'^gpx/(?P<gpx_id>[0-9]+)/delete$', views.delete_activity),
    url(r'^(?P<activity_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete$', views.delete_comment),
    url(r'^(?P<activity_id>[0-9]+)/like$', views.like_activity),
    url(r'^(?P<activity_id>[0-9]+)$', views.display_activity),
    url(r'^$', views.display_activities, name='index'),
]

FitTrackee/apps/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

FitTrackee/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation-icons/3.0/foundation-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}FitTrackee{% endblock %}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">FitTrackee</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:index' %}">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'activities:index' %}">Activities</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'activities:add' %}"><strong>Add an activity</strong></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            {% if request.user.picture %}
            <li class="nav-item">
            <div><img src="/media/{{ request.user.picture }}"
                   class="img-responsive ft_nav-profile-img"></div>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">{{ request.user.username }}</a>
            </li>
          </ul>
          {% endif %}
          <!--<form class="form-inline my-2 my-lg-0">-->
            <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
          <!--</form>-->
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
      {% block content %}
      {% endblock %}
      </div>
    </main>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

  {% block jsscript %}
  {% endblock %}

  <script>
    $(document).ready(function(){
        {% block jquery %} {% endblock %}
    })
  </script>

  </body>
</html>