FitTrackee/FitTrackee/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.auth.decorators import user_passes_test

from FitTrackee import settings
from apps.user import views as user_view
from apps.home import views as home_view

login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/home')
anonymous_forbidden = user_passes_test(lambda u: u.is_authenticated(), '/login')

urlpatterns = [
    url(r'^login/$', login_forbidden(auth_views.login), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^register/$', login_forbidden(user_view.register), name='register'),
    url(r'^users/', include('apps.users.urls')),
    url(r'^user/', include('apps.user.urls')),
    url(r'^activities/', include('apps.activities.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/',  include('apps.home.urls')),
    url(r'^profile/$', user_view.profile, name='profile'),
    url(r'^api/', include('apps.api.urls')),
    url(r'^$', anonymous_forbidden(home_view.index)),
] + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FitTrackee/apps/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^delete/picture/', views.delete_picture, name='delete-avatar'),
    url(r'^edit/', views.edit, name='edit'),
    url(r'^(?P<user_id>[0-9]+)/addFriend/(?P<friend_id>[0-9]+)$', views.add_friend),
    url(r'^(?P<user_id>[0-9]+)/removeFriend/(?P<friend_id>[0-9]+)$', views.remove_friend),
    url(r'^(?P<user_id>[0-9]+)$', views.view_user),
    url(r'^', views.profile, name='profile'),
]

FitTrackee/apps/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

FitTrackee/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Count


def get_image_path(instance, filename):
    return 'pictures/user_{0}/{1}'.format(instance.id, filename)


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    picture = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    follows = models.ManyToManyField("self", related_name='followed_users', blank=True,
                                     symmetrical=False)

    def get_activities_count(self):
        user = User.objects.filter(pk=self.id).annotate(activity__count=Count('activity'))
        return user[0].activity__count

    def get_friends(self):
        friends = self.follows.all()
        # only friends who accepted friend requests
        friends_list = [friend.id for friend in friends if self in friend.follows.all()]
        return friends_list

FitTrackee/apps/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


def validate_image_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.png', '.jpg', '.gif']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported image extension. Only *.png, *.jpg, *gif')


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class ProfileForm(UserChangeForm):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs=dict(
        readonly='readonly')))
    picture = forms.ImageField(required=False, validators=[validate_image_extension])

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'bio', 'location', 'birth_date',
                  'picture')

FitTrackee/apps/user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.http import JsonResponse
from django.db import transaction

from .forms import RegisterForm, ProfileForm
from ..activities.models import Activity
from .models import User


@login_required
def profile(request):
    activities = Activity.objects.all().order_by('-activity_date').filter(
        user_id=request.user.id)[:5]
    return render(request, 'user/profile.html', {'activities': activities})


@login_required
def edit(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'user/edit.html', {'form': form})


@login_required
def delete_picture(request):
    User.objects.get(id=request.user.id).picture.delete(save=True)
    return redirect('profile')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home:home')
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def view_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    activities = Activity.objects.all().order_by('-activity_date').filter(
        user_id=user_id)[:5]
    return render(request, 'user/display_user.html', {'ft_user': user,
                                                      'activities': activities})


@login_required
def add_friend(request, user_id, friend_id):
    print(user_id)
    print(friend_id)
    try:
        user = get_object_or_404(User, pk=user_id)
        user.follows.add(friend_id)
        user.save()
        FriendRequestSent = True
    except Exception as e:
        print(e.args)
        FriendRequestSent = False

    return JsonResponse({'FriendRequestSent': FriendRequestSent},
                        content_type='application/json')


@login_required
def remove_friend(request, user_id, friend_id):
    print(user_id)
    print(friend_id)
    try:
        with transaction.atomic():
            user = get_object_or_404(User, pk=user_id)
            user.follows.remove(friend_id)
            user.save()
            friend = get_object_or_404(User, pk=friend_id)
            friend.follows.remove(user_id)
            friend.save()
            UnFriendRequestSent = True
    except Exception as e:
        print(e.args)
        UnFriendRequestSent = False

    return JsonResponse({'FriendRequestSent': UnFriendRequestSent},
                        content_type='application/json')

FitTrackee/apps/users/views.py
from django.shortcuts import render

from ..user.models import User


def index(request):
    users = User.objects.all().order_by('-date_joined')[:10]
    return render(request, 'users/display_users.html', {'ft_users': users})

FitTrackee/templates/user/display_user.html
{% extends 'base.html' %}

{% block title %}FitTrackee - {{ft_user.username}}{% endblock %}

{% block content %}

        <div class="container">
            <h2 class="ft_title">Profile</h2>
            <div class="row">
              <div class="col-md-8">
                  <div class="card">
                      <div class="card-header">
                        {{ ft_user.username }}
                      </div>
                      <div class="card-body">
                          <div class="row">
                              <div class="col-md-8">
                                  <p>First name : {{ ft_user.first_name }}</p>
                                  <p>Last name : {{ ft_user.last_name }}</p>
                                  <p>Email : {{ ft_user.email }}</p>
                                  <p>Bio : {{ ft_user.bio }}</p>
                                  <p>Location : {{ ft_user.location }}</p>
                                  <p>Birth date : {{ ft_user.birth_date }}</p>
                                  <p>Registration date : {{ ft_user.date_joined }}</p>
                              </div>
                              {% if ft_user.picture %}
                              <div class="col-md-4 mx-auto d-block text-center">
                                  <img src="/media/{{ ft_user.picture }}"
                                       class="img-fluid ft_profile-img">
                              </div>
                              {% endif %}
                          </div>
                      </div>
                    </div>
              </div>
              <div class="col-md-4">
                  <div class="card">
                      <div class="card-header">
                        Last activities
                      </div>
                      <div class="card-body">
                        {% if activities %}
                          <ul>
                        {% for activity in activities %}
                            <li class="nav-item">
                              <a class="nav-link" href='/activities/{{activity.id}}'>{{activity}}</a>
                            </li>
                        {% endfor %}
                          </ul>
                        {% else %}
                          <p>No activities for now...</p>
                        {% endif %}
                      </div>
                    </div>
              </div>
            </div>
        </div>

{% endblock %}

FitTrackee/templates/user/edit.html
{% extends 'base.html' %}

{% block title %}FitTrackee - Edit Profile{% endblock %}

{% block content %}

        <div class="container ft_profileForm">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="card text-center">
                        <h2 class="card-header">Profile</h2>
                        <div class="card-body">
                            <form enctype="multipart/form-data" method="post">
                            {%csrf_token%}
                            {% for error in form.non_field_errors %}
                            <div class="form-group has-errors text-danger small">
                                {{error}}
                            </div>profileForm
                            {% endfor %}

                            {% for field in form %}
                            <div class="form-group has-errors text-danger small">
                                {{field.errors}}
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 col-form-label">
                                {{field.label}}
                                </div>
                                <div class="col-md-8">
                                {{field}}
                                </div>
                            </div>
                            {% endfor %}
                            <button class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>

{% endblock %}

FitTrackee/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}FitTrackee - Profile{% endblock %}

{% block content %}

        <div class="container">
            <h2 class="ft_title">Profile</h2>
            <div class="row">
              <div class="col-md-8">
                  <div class="card">
                      <div class="card-header">
                        {{ request.user.username }} <a href="{% url 'user:edit' %}"><i
                              class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                      </div>
                      <div class="card-body">
                          <div class="row">
                              <div class="col-md-8">
                                  <p>First name : {{ request.user.first_name }}</p>
                                  <p>Last name : {{ request.user.last_name }}</p>
                                  <p>Email : {{ request.user.email }}</p>
                                  <p>Bio : {{ request.user.bio }}</p>
                                  <p>Location : {{ request.user.location }}</p>
                                  <p>Birth date : {{ request.user.birth_date }}</p>
                                  <p>Registration date : {{ request.user.date_joined }}</p>
                              </div>
                              {% if request.user.picture %}
                              <div class="col-md-4 mx-auto d-block text-center">
                                  <img src="/media/{{ request.user.picture }}"
                                       class="img-fluid ft_profile-img">
                                  <p><a href="{% url 'user:delete-avatar' %}">delete image</a></p>
                              </div>
                              {% endif %}
                          </div>
                      </div>
                    </div>
              </div>
              <div class="col-md-4">
                  <div class="card">
                      <div class="card-header">
                        Last activities
                      </div>
                      <div class="card-body">
                        {% if activities %}
                          <ul>
                        {% for activity in activities %}
                            <li class="nav-item">
                              <a class="nav-link" href='/activities/{{activity.id}}'>{{activity}}</a>
                            </li>
                        {% endfor %}
                          </ul>
                        {% else %}
                          <p>No activities for now...</p>
                        {% endif %}
                      </div>
                    </div>
              </div>
            </div>

            <div class="row">
                <div class="col-md-8">

                    {% if request.user.follows.all %}
                    <ul>
                        <br><h3>Friends</h3>
                    {% for friend in request.user.follows.all %}
                      <div class="card ft_activities">
                          <div class="card-header">
                              <a href="/user/{{friend.id}}">{{friend.username}}</a>
                              {% if ft_user.id != request.user.id %}
                                  {% if friend in request.user.follows.all and request.user in friend.follows.all %}
                                  <a href="#" class="badge badge-primary friendAction"
                                     id="removeFriend-{{friend.id}}"><i
                                          class="fa fa-user-times"></i></a>
                                  {% elif friend in request.user.follows.all and not request.user in friend.follows.all %}
                                  <span class="badge badge-warning"><i class="fa fa-user"></i>
                                      friend request pending</span>
                                  {% elif not friend in request.user.follows.all and request.user in friend.follows.all %}
                                  <a href="#" class="badge badge-info friendAction"
                                     id="addFriend-{{friend.id}}"><i class="fa fa-user-plus"></i>
                                      waiting your response</a>
                                  {% endif %}
                              {% endif %}
                          </div>
                          <div class="card-body">
                              <div class="row">
                                  <div class="col-md-8">
                                      <p>Joined: {{friend.date_joined}}</p>
                                      <p>Activities: {{friend.get_activities_count}}</p>
                                  </div>

                                  {% if friend.picture %}
                                  <div class="col-md-4 mx-auto d-block text-center">
                                      <img src="/media/{{ friend.picture }}"
                                           class="img-fluid ft_profile-img-small">
                                  </div>
                                  {% endif %}
                              </div>
                          </div>
                      </div>
                      {% endfor %}
                    </ul>
                    {% else %}
                    <br>
                    <p class="text-center">No friends for now...</p>
                    {% endif %}
                    <p class="text-center"><a href="{% url 'users:index' %}">Search for
                        friends</a></p>
                </div>
            </div>
        </div>

{% endblock %}

    <script>
{% block jquery %}

$('.friendAction').click(function () {

    var id = $(this).attr("id");
    var action = id.split("-");
    var url = '/user/{{ request.user.id }}/' + action[0] + '/' + action[1];

    $.ajax({
    method: "GET",
    url: url,
    success: function(data){
        window.location = "/profile"
        },
        error: function(error_data){
            console.log("error");
            console.log(error_data);
        }
    });
});

{% endblock %}
    </script>

FitTrackee/templates/user/register.html
{% extends 'base.html' %}

{% block title %}FitTrackee - Register{% endblock %}

{% block content %}

        <div class="container ft_form">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="card text-center">
                        <h2 class="card-header">Register</h2>
                        <div class="card-body">
                            <form method="post">
                            {%csrf_token%}
                            {% for error in form.non_field_errors %}
                            <div class="form-group has-errors text-danger small">
                                {{error}}
                            </div>
                            {% endfor %}

                            {% for field in form %}
                            <div class="form-group has-errors text-danger small">
                                {{field.errors}}
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 col-form-label">
                                {{field.label}}
                                </div>
                                <div class="col-md-8">
                                {{field}}
                                </div>
                            </div>
                            {% endfor %}
                            <button class="btn btn-primary">Register</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>

{% endblock %}